# Generated by Django 5.1.4 on 2024-12-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='metadata',
        ),
        migrations.AddField(
            model_name='tag',
            name='metadata',
            field=models.ManyToManyField(to='core.metadata'),
        ),
    ]
